import path from 'path'
import { existsSync, readFileSync } from 'fs'
import { createJiti } from 'jiti'
import { type MeoCordConfig } from '@src/interface/index.js'
import { fixJSON } from '@src/util/json.util.js'

let cachedConfig: MeoCordConfig | undefined
let configLoaded = false

/**
 * Loads the MeoCord configuration, checking compiled output first then falling back to source.
 *
 * Resolution order:
 * 1. `dist/meocord.config.mjs` — pre-compiled by `meocord build`, no tsconfig or source files needed
 * 2. `meocord.config.ts` — loaded via jiti with tsconfig path aliases (dev mode)
 *
 * The result is cached after the first successful load.
 *
 * @returns {MeoCordConfig | undefined} The loaded configuration object, or undefined if loading fails.
 */
export function loadMeoCordConfig(): MeoCordConfig | undefined {
  if (configLoaded) return cachedConfig

  configLoaded = true
  cachedConfig = loadCompiledConfig() ?? loadSourceConfig()
  return cachedConfig
}

/**
 * Loads the pre-compiled config from dist/meocord.config.mjs.
 * This file is generated by `meocord build` and requires no tsconfig or source files.
 */
function loadCompiledConfig(): MeoCordConfig | undefined {
  const compiledPath = path.resolve(process.cwd(), 'dist', 'meocord.config.mjs')
  if (!existsSync(compiledPath)) return undefined

  try {
    const jiti = createJiti(import.meta.url, { interopDefault: true })
    return jiti(compiledPath) as MeoCordConfig
  } catch {
    // Fall through to source config
    return undefined
  }
}

/**
 * Loads the source config from meocord.config.ts via jiti with tsconfig path alias resolution.
 * Used in development mode where source files and tsconfig.json are available.
 */
/**
 * Loads meocord.config.ts from source, every time, for configuring a build.
 *
 * {@link loadMeoCordConfig} prefers the compiled `dist/meocord.config.mjs` and caches the result,
 * which is right at runtime -- production has no source -- and wrong while building. The compiled
 * file is the previous build's output, so a build that read it ran on the config as it was last
 * time: an edit to `meocord.config.ts` took effect only on the build after next. Whatever read the
 * config first in the process also fixed it for the rest, so the watcher's reload on a config
 * change reloaded nothing. Build time always has the source, so it reads the source.
 */
export function loadMeoCordSourceConfig(): MeoCordConfig | undefined {
  return loadSourceConfig()
}

function loadSourceConfig(): MeoCordConfig | undefined {
  const configPath = path.resolve(process.cwd(), 'meocord.config.ts')
  if (!existsSync(configPath)) return undefined

  try {
    const tsConfigPath = path.resolve(process.cwd(), 'tsconfig.json')
    const aliases: Record<string, string> = {}

    if (existsSync(tsConfigPath)) {
      const tsConfig = JSON.parse(fixJSON(readFileSync(tsConfigPath, 'utf-8')))
      const paths = tsConfig?.compilerOptions?.paths

      if (paths) {
        for (const [key, values] of Object.entries(paths)) {
          const aliasKey = key.replace('/*', '')
          aliases[aliasKey] = path.resolve(process.cwd(), (values as string[])[0].replace('/*', ''))
        }
      }
    }

    const jiti = createJiti(import.meta.url, {
      interopDefault: true,
      alias: aliases,
      moduleCache: false,
    })

    return jiti(configPath) as MeoCordConfig
  } catch (error) {
    if (error instanceof Error) {
      console.error(`[MeoCord] Failed to load config: ${error.message}`)
    } else {
      console.error(`[MeoCord] Failed to load config: Unknown error`)
    }
    return undefined
  }
}
