/**
 * Writes THIRD_PARTY_NOTICES.md from the packages MeoCord depends on, as installed.
 *
 * Generated rather than written by hand so it cannot drift: `--check` compares the file against
 * what would be generated -- formatted by prettier, like every other Markdown file -- and fails when
 * they differ, which is how CI catches a dependency added without its notice. Versions are left out on purpose -- they change with every update, and the
 * license and source of a package do not.
 *
 *   bun scripts/third-party-notices.ts          write the file
 *   bun scripts/third-party-notices.ts --check  fail if it is out of date
 */

import { existsSync, readFileSync, writeFileSync } from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'
import { format, resolveConfig } from 'prettier'

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const outputPath = path.join(repoRoot, 'THIRD_PARTY_NOTICES.md')

interface Manifest {
  dependencies?: Record<string, string>
  peerDependencies?: Record<string, string>
  license?: string | { type?: string }
  repository?: string | { url?: string }
  homepage?: string
}

function readManifest(dir: string): Manifest {
  return JSON.parse(readFileSync(path.join(dir, 'package.json'), 'utf8')) as Manifest
}

function licenseOf(manifest: Manifest): string {
  if (typeof manifest.license === 'string') return manifest.license
  return manifest.license?.type ?? 'UNKNOWN'
}

/** A browsable URL for a package's source, from the forms `repository` takes in practice. */
function sourceOf(name: string, manifest: Manifest): string {
  const raw = typeof manifest.repository === 'string' ? manifest.repository : manifest.repository?.url
  if (!raw) return manifest.homepage ?? `https://www.npmjs.com/package/${name}`

  const url = raw
    .replace(/^git\+/, '')
    .replace(/^git:\/\//, 'https://')
    .replace(/^ssh:\/\/git@/, 'https://')
    .replace(/^git@github\.com:/, 'https://github.com/')
    .replace(/\.git$/, '')
  // `owner/repo` and `github:owner/repo` are shorthands for GitHub.
  if (/^(github:)?[\w.-]+\/[\w.-]+$/.test(url)) return `https://github.com/${url.replace(/^github:/, '')}`
  return url
}

function table(names: string[]): string {
  const rows = names.map(name => {
    const dir = path.join(repoRoot, 'node_modules', name)
    if (!existsSync(path.join(dir, 'package.json'))) {
      throw new Error(`${name} is not installed; run \`bun install\` before generating notices.`)
    }
    const manifest = readManifest(dir)
    return `| [${name}](https://www.npmjs.com/package/${name}) | ${licenseOf(manifest)} | ${sourceOf(name, manifest)} |`
  })
  return ['| Package | License | Source |', '| --- | --- | --- |', ...rows].join('\n')
}

function generate(): string {
  const own = readManifest(repoRoot)
  const dependencies = Object.keys(own.dependencies ?? {}).sort()
  const peers = Object.keys(own.peerDependencies ?? {}).sort()

  return `# Third-Party Notices

MeoCord is licensed under the [MIT License](./LICENSE). It depends on the open-source packages
below, each under its own license.

None of their code is copied into MeoCord's published package: npm installs each one alongside
MeoCord, with its own license file. This list is a record of what MeoCord relies on, and of the
terms those packages are offered under.

## Dependencies

Installed with MeoCord.

${table(dependencies)}

## Peer dependencies

Installed by the application using MeoCord.

${table(peers)}

---

Generated by \`scripts/third-party-notices.ts\` from the installed packages. Run
\`bun run notices\` after adding or removing a dependency.
`
}

// Formatted the same way `bun run format` formats every other Markdown file, so the file is never
// exempt from prettier and the check below compares against what prettier would leave.
const generated = await format(generate(), { ...(await resolveConfig(outputPath)), filepath: outputPath })

if (process.argv.includes('--check')) {
  const current = existsSync(outputPath) ? readFileSync(outputPath, 'utf8') : ''
  if (current !== generated) {
    console.error('THIRD_PARTY_NOTICES.md is out of date. Run `bun run notices` and commit the result.')
    process.exit(1)
  }
  console.log('THIRD_PARTY_NOTICES.md is up to date.')
} else {
  writeFileSync(outputPath, generated)
  console.log(`Wrote ${path.relative(repoRoot, outputPath)}`)
}
